# 6.1 Basic list and array operations

In [24]:
#1
import numpy
from numpy import *
my_list = [6,24,2.5,'labtime',sqrt(2)]
print(my_list)
#a
index = my_list.index('labtime')
print(index)
#b
my_list2 = [3,1,4,15,6]
print(my_list2)
my_list3 = my_list + my_list2
print(my_list3)
#c
my_list3.remove(15)
print('updated my_list3 list',my_list3)

[6, 24, 2.5, 'labtime', 1.4142135623730951]
3
[3, 1, 4, 15, 6]
[6, 24, 2.5, 'labtime', 1.4142135623730951, 3, 1, 4, 15, 6]
updated my_list3 list [6, 24, 2.5, 'labtime', 1.4142135623730951, 3, 1, 4, 6]


In [58]:
#2
import numpy as np

apple = np.linspace(0,42, num=15)
print(apple)
apple.size  

[ 0.  3.  6.  9. 12. 15. 18. 21. 24. 27. 30. 33. 36. 39. 42.]


15

In [62]:
#3
import numpy as np 

orange = np.linspace(18,-18, num=9)
print(orange)
orange.size

[ 18.   13.5   9.    4.5   0.   -4.5  -9.  -13.5 -18. ]


9

In [112]:
#4
list = []
ratio=(61-5)/15
for i in range (0,16):
    list.append(5+(ratio*i))
print(list)
len(list)

[5.0, 8.733333333333334, 12.466666666666667, 16.2, 19.933333333333334, 23.666666666666668, 27.4, 31.133333333333333, 34.86666666666667, 38.6, 42.333333333333336, 46.06666666666667, 49.8, 53.53333333333333, 57.266666666666666, 61.0]


16

In [119]:
#5
#a),b)
name_1= 'Niklas ' 
name_2= 'Feil-Ho'
fullname= name_1+name_2
print(fullname)

Niklas Feil-Ho


In [3]:
#6
#a.)
import numpy as np

Afirst = np.linspace(3,51, num=13)
print(Afirst)
Afirst.size
#b.)
Asecond= np.zeros(7)
Asecond[0:4]=Afirst[0:4]
Asecond[-3:]=Afirst[-3:]
print(Asecond)

[ 3.  7. 11. 15. 19. 23. 27. 31. 35. 39. 43. 47. 51.]
[ 3.  7. 11. 15. 43. 47. 51.]


# 6.2 More vectors, 2D arrays and vectorization 

In [160]:
#1
import numpy as np

w = np.linspace(0,3,num=31)
print(w)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3. ]


In [167]:
w[:]
#this array is being printed as 0.1 ascending order

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. ])

In [164]:
w[:-2]

#this array is printing elements in in a 0.1 ascending order with
#a limit of 0.2 under the original range 

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8])

In [165]:
w[::5]
#This array is printing values in a 0.5 incremental order

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. ])

In [168]:
w[2:-2:6]
#This array has been increased initially by 0.2 then by 0.6 then by 0.6
#followed by 0.6 and finally with 0.6

array([0.2, 0.8, 1.4, 2. , 2.6])

In [181]:
#2
import numpy as np

ben = np.linspace(0,1,num=5)
print(Ben)
scoop = np.linspace(0,1.2,num=6).reshape(2,3)
print(scoop)
print(type(ben))
print(type(scoop))
print(len(ben))
print(len(scoop))
print(shape(ben))
print(shape(scoop))
print(size(ben))
print(size(ben))

[0.   0.25 0.5  0.75 1.  ]
[[0.   0.24 0.48]
 [0.72 0.96 1.2 ]]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
5
2
(5,)
(2, 3)
5
5


In [183]:
whos

Variable                    Type                          Data/Info
-------------------------------------------------------------------
ALLOW_THREADS               int                           1
Afirst                      ndarray                       13: 13 elems, type `float64`, 104 bytes
Apple                       ndarray                       15: 15 elems, type `float64`, 120 bytes
Asecond                     ndarray                       7: 7 elems, type `float64`, 56 bytes
AxisError                   type                          <class 'numpy.AxisError'>
BUFSIZE                     int                           8192
Ben                         ndarray                       5: 5 elems, type `float64`, 40 bytes
Bytes0                      type                          <class 'numpy.bytes_'>
CLIP                        int                           0
ComplexWarning              type                          <class 'numpy.ComplexWarning'>
DataSource                  type         

In [186]:
#3
import numpy as np

cloud= np.linspace(0,1,num=5)
print(len(cloud))
# len showed me how many elements are in the vector
print(min(cloud))
# min showed me the minimum value of the vector
print(max(cloud))
# max showed me the maximum value of the vector
print(sum(cloud))
# sum showed me the sum of all the values within the vector
print(sorted(cloud))
# sorted sorted all the values within the vector from min to max
print(sort(cloud))  
# sort does the sane thing as sorted except doesn't show decimal of 0

5
0.0
1.0
2.5
[0.0, 0.25, 0.5, 0.75, 1.0]
[0.   0.25 0.5  0.75 1.  ]


In [191]:
#4
import numpy as np

b1 = np.linspace(0,28, num=8)
b2 = np.linspace(69,62,num=8)
b3= np.linspace(1.4,0.7,num=8)
b=np.vstack((b1,b2,b3))
print(b)

[[ 0.   4.   8.  12.  16.  20.  24.  28. ]
 [69.  68.  67.  66.  65.  64.  63.  62. ]
 [ 1.4  1.3  1.2  1.1  1.   0.9  0.8  0.7]]


In [196]:
#5
b[:,3]
b_5=np.linspace(1,3,num=3)
print(b_5)
b[:,3]=b_5
print(b)

[1. 2. 3.]
[[ 0.   4.   8.   1.  16.  20.  24.  28. ]
 [69.  68.  67.   2.  65.  64.  63.  62. ]
 [ 1.4  1.3  1.2  3.   1.   0.9  0.8  0.7]]


In [222]:
#6
#a.)
import numpy as np

msame_1_2 = np.linspace(7,7,num=10).reshape(2,5)
print(msame_1_2)

[[7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7.]]


In [224]:
#b.)
msame_3 = np.linspace(0,0,num=5)
msame_4 = np.linspace(1,5,num=5)
msame = np.vstack((msame_1_2,msame_3,msame_4))
print(msame)



[[7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7.]
 [0. 0. 0. 0. 0.]
 [1. 2. 3. 4. 5.]]


In [229]:
#c.)
msame[1]
msame_5 = msame[1]*6
msame_final = np.vstack((msame_1_2,msame_3,msame_4,msame_5))
print(msame_final)

[[ 7.  7.  7.  7.  7.]
 [ 7.  7.  7.  7.  7.]
 [ 0.  0.  0.  0.  0.]
 [ 1.  2.  3.  4.  5.]
 [42. 42. 42. 42. 42.]]


In [248]:
#d.)
concatenate = np.hstack((b,(msame_final[1:4,:])))
print(concatenate)

[[ 0.   4.   8.   1.  16.  20.  24.  28.   7.   7.   7.   7.   7. ]
 [69.  68.  67.   2.  65.  64.  63.  62.   0.   0.   0.   0.   0. ]
 [ 1.4  1.3  1.2  3.   1.   0.9  0.8  0.7  1.   2.   3.   4.   5. ]]


In [253]:
#7 dot product
import numpy as np

a= np.linspace(1,3,num=3)
b=np.linspace(4,6,num=3)
print(np.sum(a*b))

32.0
